// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelManagement.DataAccessLayer.Entities;

#nullable disable

namespace TravelManagement_DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506160751_MakeVehicleIDNullable")]
    partial class MakeVehicleIDNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelManagement.Core.Models.AgentCashCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AmountCollected")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("AgentCashCollections");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("Assigned")
                        .HasColumnType("boolean");

                    b.Property<int>("BookingType")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerID")
                        .HasColumnType("integer");

                    b.Property<int?>("ExternalEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<int>("Pax")
                        .HasColumnType("integer");

                    b.Property<int>("Payment")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Payments")
                        .HasColumnType("integer[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("To")
                        .HasColumnType("text");

                    b.Property<int?>("TravelAgentId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("Traveltime")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("Userid")
                        .HasColumnType("integer");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("travelDate")
                        .HasColumnType("date");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ExternalEmployeeId");

                    b.HasIndex("TravelAgentId");

                    b.HasIndex("Userid");

                    b.HasIndex("VehicleId");

                    b.HasIndex("travelDate");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.BookingPaymentAllocation", b =>
                {
                    b.Property<int>("PaymentAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentAllocationId"));

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomersId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PayerType")
                        .HasColumnType("integer");

                    b.Property<int?>("TravelAgentId")
                        .HasColumnType("integer");

                    b.HasKey("PaymentAllocationId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomersId");

                    b.HasIndex("TravelAgentId");

                    b.ToTable("BookingPaymentAllocations");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.Customers", b =>
                {
                    b.Property<int>("CustomersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomersId"));

                    b.Property<string>("AlternateNumber")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("text");

                    b.Property<DateOnly>("TravelDate")
                        .HasColumnType("date");

                    b.HasKey("CustomersId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.Documents", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text");

                    b.Property<string>("DriverName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<bool>("HasExpiry")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("VehicleID")
                        .HasColumnType("integer");

                    b.HasKey("DocumentID");

                    b.HasIndex("VehicleID");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.EmailInquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("text");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("boolean");

                    b.Property<int>("Pax")
                        .HasColumnType("integer");

                    b.Property<string>("To")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("TravelDate")
                        .HasColumnType("date");

                    b.Property<string>("VehicleName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmailInquiries");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.ExternalEmployee", b =>
                {
                    b.Property<int>("externalEmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("externalEmployeeID"));

                    b.Property<string>("externalEmployeeName")
                        .HasColumnType("text");

                    b.Property<string>("externalEmployeeNumber")
                        .HasColumnType("text");

                    b.HasKey("externalEmployeeID");

                    b.ToTable("ExternalEmployees");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.ExternalEmployeeCashCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BookingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("CashCollectedBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("CommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ExternalEmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("TotalPaidToVendor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ExternalEmployeeId");

                    b.ToTable("ExternalEmployeeCashCollections");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.OvertimeLog", b =>
                {
                    b.Property<int>("OvertimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OvertimeID"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<decimal>("hours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("OvertimeID");

                    b.HasIndex("BookingId");

                    b.HasIndex("userId");

                    b.ToTable("overtimeLogs");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.Payments", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<int?>("TravelAgentId")
                        .HasColumnType("integer");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TravelAgentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.RateChart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AgentName")
                        .HasColumnType("text");

                    b.Property<string>("AgentNumber")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FooterJson")
                        .HasColumnType("text");

                    b.Property<string>("Locations")
                        .HasColumnType("text");

                    b.Property<string>("NotesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PeakSeasonDates")
                        .HasColumnType("text");

                    b.Property<string>("RoutesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeasonMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialDaysNote")
                        .HasColumnType("text");

                    b.Property<string>("SurchargesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VehiclesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RateCharts");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.Salary", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalaryId"));

                    b.Property<decimal>("BaseSalay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Deduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetSalaey")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Overtimepay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("SalaryId");

                    b.HasIndex("userID", "Month", "Year");

                    b.ToTable("salaries");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.TravelAgent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AgentId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<decimal>("CommissionPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("CommissionRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("IFSC")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("text");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("text");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("AgentId");

                    b.ToTable("TravelAgents");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("EmployeAge")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EmployeeDOB")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSalaryActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAutoSalaryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Licence")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RenewalMailSentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResetPasswordtoken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RestPasswordExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SalaryDay")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("userId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleId"));

                    b.Property<decimal>("EMIAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("EMIDay")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EMIEndDate")
                        .HasColumnType("date");

                    b.Property<string>("EMILender")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EMIStartDate")
                        .HasColumnType("date");

                    b.Property<bool>("HasEMI")
                        .HasColumnType("boolean");

                    b.Property<int>("PaidEMIs")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<int>("Seatingcapacity")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEMIs")
                        .HasColumnType("integer");

                    b.Property<double>("VehicleAge")
                        .HasColumnType("double precision");

                    b.Property<string>("VehicleName")
                        .HasColumnType("text");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("text");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.VehicleExpence", b =>
                {
                    b.Property<int>("VehicleExpenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleExpenceId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("VehicleID")
                        .HasColumnType("integer");

                    b.HasKey("VehicleExpenceId");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("VehicleID");

                    b.ToTable("vehicleExpences");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.VehicleMaintenanceShedule", b =>
                {
                    b.Property<int>("VechicleMaintenanceSheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VechicleMaintenanceSheduleId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("Nextduedate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ServieDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VehicleID")
                        .HasColumnType("integer");

                    b.Property<decimal>("cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("maintenanceType")
                        .HasColumnType("integer");

                    b.HasKey("VechicleMaintenanceSheduleId");

                    b.HasIndex("VehicleID");

                    b.ToTable("vehicleMaintenanceShedules");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.AgentCashCollection", b =>
                {
                    b.HasOne("TravelManagement.Core.Models.TravelAgent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.Booking", b =>
                {
                    b.HasOne("TravelManagement.Core.Models.Customers", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManagement.Core.Models.ExternalEmployee", "ExternalEmployee")
                        .WithMany()
                        .HasForeignKey("ExternalEmployeeId");

                    b.HasOne("TravelManagement.Core.Models.TravelAgent", "TravelAgent")
                        .WithMany()
                        .HasForeignKey("TravelAgentId");

                    b.HasOne("TravelManagement.Core.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("Userid");

                    b.HasOne("TravelManagement.Core.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("Customer");

                    b.Navigation("ExternalEmployee");

                    b.Navigation("TravelAgent");

                    b.Navigation("Vehicle");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.BookingPaymentAllocation", b =>
                {
                    b.HasOne("TravelManagement.Core.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManagement.Core.Models.Customers", "Customers")
                        .WithMany()
                        .HasForeignKey("CustomersId");

                    b.HasOne("TravelManagement.Core.Models.TravelAgent", "TravelAgent")
                        .WithMany()
                        .HasForeignKey("TravelAgentId");

                    b.Navigation("Booking");

                    b.Navigation("Customers");

                    b.Navigation("TravelAgent");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.Documents", b =>
                {
                    b.HasOne("TravelManagement.Core.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleID");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.ExternalEmployeeCashCollection", b =>
                {
                    b.HasOne("TravelManagement.Core.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManagement.Core.Models.ExternalEmployee", "ExternalEmployee")
                        .WithMany()
                        .HasForeignKey("ExternalEmployeeId");

                    b.Navigation("Booking");

                    b.Navigation("ExternalEmployee");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.OvertimeLog", b =>
                {
                    b.HasOne("TravelManagement.Core.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManagement.Core.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.Payments", b =>
                {
                    b.HasOne("TravelManagement.Core.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelManagement.Core.Models.Customers", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("TravelManagement.Core.Models.TravelAgent", "TravelAgent")
                        .WithMany()
                        .HasForeignKey("TravelAgentId");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("TravelAgent");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.Salary", b =>
                {
                    b.HasOne("TravelManagement.Core.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.VehicleExpence", b =>
                {
                    b.HasOne("TravelManagement.Core.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleID");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TravelManagement.Core.Models.VehicleMaintenanceShedule", b =>
                {
                    b.HasOne("TravelManagement.Core.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
